sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - v4
  - lts/*
  - stable
after_success:
  - npm run semantic-release
env:
  global:
    - secure: "HTKHmCn2kVJ7/s5jg5ZzMA4GlAuvCJeKb3J2V6Ks8irjHpCVeqsmXtkVqN4gveOqH9wFUZmwjPCzE6QiVavNV8Q/Vveh9d+6d3BeRHHghlkagD1MHwUesCTDFSaP4TNJLk/txxvP44XO5PI4I8881CSQ92TiL6T3X4jjs/C3Z9XifAucPz32yyUaq08a5/vVyVc10g3H2Sc2bLCAnB/hk37KYrwQ/Cf8PM64moscOQrB2ESMYbDKd5VElxN97c7SYCLQfa04renLmV6rNARIZ+00oxRJBiBKGL+VFC55qtLv24kzmWVR87RVR46WAUrLWDXK1FkVSnVCGGutAaJU0wCqkIDRD7AwUHJWq/2jgsS3ysHUHsoXWiRlglnP6zCrmsl4O4FsbsObUdTy0jLP6FEUyI+yg3zue1bkvyUMEp9jGfq/sJh/7tT4ao7Qt35/qXILS9u2eQRJIZpNna4bUGG7i/H0sh5nSxNufOnTvu7SPno+pKI1pLw6/9HL6dv9B2J05+wDecWgOiRaCBt5vU6oHoDO25CzjcnrNUhuyLkqxiV4srWMKkPxAqPD20WcDCjr/v/SKK90aNyqlp1UEXSzuNVRK9RJ4PulFW5cNHJdl1c+GO22fu04rY+VqhktoDPReBrnS8scwfiNjyPggW2ZF2lYLnm+OlKw20hE6DE="
    - secure: "rg4tqR4y6MyJ3kyFFk9rqAfaJmvbElzPlbhIxKvMEYew62sf1CfveV1Y97t6oxbyAdpdeX8rjBreFnaoxcPUtpTmhnzR1rb/A9ZeN0a88AyMWmZSeHhgl2CzXVgMKe+RHwip0JmkSWM7xJBAgK09UAfEZp6CcVSckjad2Jr1zK2/ND7JK9Jq/JKFn2pKp7B35DooqwTG4tco54xf9rYcQ87l5NFThJew/RogVSrXRrkBkSm8Q1CJSmIjbvsPkj/xsAm2N1PVOntw2q+yzQUZEl7YDKqgDGIez0fyqL4dSZw70hxq2TJH+GQo/2yi4V1fm8V+INKNCzOZGrGLacU5vYr7BXbrn6/i8BbxlJ5LqIgDTWbvF6J06AGyM0hwPlvVmZOcoQsGTVzJKwrE6XIMoTgkZJNjVZUqCtKb/FkpN9jkDVeQK5bIF59doBGFBthJnizlwd6SRmdHXxpnYs1aCsxwR1GnePZ6CzGe2H8we/fdk6GIdIfkvqCx1WwrFIQPZoD1BeITNNmXmUp3HtEXk6cpeT5iYSpFCtzr92o9mey4FAzVRDfVQedDdnHvQX/2iXv7/aWElLNPE2IVX6AgCPXK/TEKTabr/Cc85aI8MRdWrlBCi5DmSd9V5kbW4yJpsZt5lv4jihle867qYpc8XM9j3/4QUPuAGMg9Vg8QMP4="
